### ISSUE TITLE
`ubus call poe info` won't refresh/reflect current realtime connected devices after a while

### ISSUE THREAD

**Issue by walterav1984** [Hurricos/realtek-poe#21]
ZyXEL GS1900-24HPv1
realtek-poe versions from the beginning till CI41 affected

After a couple of PoE device port swaps (re)connecting the `ubus call poe info` won't reflect/update the current correct status for example if port 13 and port 14 were connected delivering PoE and I swap over devices to port 15 and 16 the status would still report port 13 and port 14 being active and delivering power. The PoE mechanism is still active though and new (re)connected devices still receive power.

The only remedy for this like the all port status `unknown` issue #10 is to restart not reload the `/etc/init.d/poe restart` service. The root cause might even be the same as issue #10 because that eventually is also a hang/stuck on realtime refresh of port status.

Sometimes you can port swap more than 24 for ports before this issue shows up, and sometimes after 2 or 3 port swaps.

**Comment by mrnuke** [comment]
Does this still happen with [CI57](https://github.com/Hurricos/realtek-poe/actions/runs/2821874633) ?

**Comment by mrnuke** [comment]
Given we haven't seen any complaints about this in the past two weeks, I am closing this as resolved.

On a side note, the underlying issue is bytes being dropped on the RX side. The packetizer won't catch that, and will keep reading packets with an off-by-n offset. If we see that in the wild, then we'll have to open a new bug.
