### ISSUE TITLE
Version tags and releases

### ISSUE THREAD

**Issue by yurtpage** [Hurricos/realtek-poe#34]
Could you please add a git tag for a release version and ideally also create a release on the GitHub
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

This is a common practice and helps a lot for package maintainers.

**Comment by yurtpage** [comment]
Sorry, I see that the repo has a tag v1.0
The problem is that in the OpenWrt is used a version with a commit hash 39c93d39dd10da77b4fe48bc1d6bdd3c5978f866
So could you please tag the commit with v1.1.0 e.g. release it as version

**Comment by mrnuke** [comment]
The latest commit is tagged -- also the same that is used in OpenWRT feeds. What is the problem with the current tagging system?

![image](https://github.com/Hurricos/realtek-poe/assets/2610559/321dd1fd-97ef-4415-ba61-3bb519a8232e)

**Comment by yurtpage** [comment]
I see, sorry, I didn't checked that the last commit **is** the v1.0.
In the OpenWrt Makfile anyway used not a tag but a commit hash:
```
PKG_SOURCE_URL:=https://github.com/Hurricos/realtek-poe.git
PKG_SOURCE_VERSION:=39c93d39dd10da77b4fe48bc1d6bdd3c5978f866
```

Thank you

**Comment by mrnuke** [comment]
@yurtpage , we use commit hashes in the OpenWRT build because those cannot be modified after the fact. A git commit --amend or new commits would cause the hash to change and someone will notice. A tag can be moved silently.

There is a case to be made about having human-readable version numbers, we just haven't looked deeply into it. So far, our approach has been to recommend the latest version in the OpenWRT repos., unless testing a new fewature or recent bugfix.

**Comment by yurtpage** [comment]
Thank you for answering. Maybe we can use the PKG_HASH for validation? It's SHA256 which is better than the git's SHA1 of commit
